# Generated by Django 5.2.8 on 2025-11-24 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_wuliao', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单号')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='订单状态')),
                ('product_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='产品编号')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('plan_delivery', models.DateField(blank=True, null=True, verbose_name='计划交付日期')),
                ('owner', models.CharField(blank=True, max_length=50, null=True, verbose_name='制单员')),
                ('wh', models.CharField(blank=True, max_length=50, null=True, verbose_name='仓库员')),
                ('audit', models.CharField(blank=True, max_length=50, null=True, verbose_name='审计员')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本')),
                ('lot_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='批次号')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '2.0 生产订单',
                'verbose_name_plural': '2.0 生产订单',
                'db_table': '[b_jihua].[Order]',
                'ordering': ['deadline', 'status'],
            },
        ),
        migrations.CreateModel(
            name='OrderParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='状态')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='交货日期')),
                ('plan_delivery', models.DateField(blank=True, null=True, verbose_name='计划交付日期')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('defectives', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='不良品数量')),
                ('deliveries', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='交付数量')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='成本')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_wuliao.material', verbose_name='物料编号')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_jihua.order', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '2.1 订单详情',
                'verbose_name_plural': '2.1 订单详情',
                'db_table': '[b_jihua].[OrderParts]',
                'ordering': ['deadline', 'status'],
                'unique_together': {('order', 'material')},
            },
        ),
    ]
