# Generated by Django 5.2.8 on 2025-11-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_jihua', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plan_delivery',
        ),
        migrations.RemoveField(
            model_name='orderparts',
            name='plan_delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_day',
            field=models.DateField(blank=True, null=True, verbose_name='交货日期'),
        ),
        migrations.AddField(
            model_name='orderparts',
            name='delivery_day',
            field=models.DateField(blank=True, null=True, verbose_name='交货日期'),
        ),
        migrations.AlterField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='计划交付日期'),
        ),
        migrations.AlterField(
            model_name='orderparts',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='计划交付日期'),
        ),
    ]
