# Generated by Django 5.2.8 on 2025-11-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_jihua', '0002_remove_order_plan_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderparts',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='版本'),
        ),
    ]
