# Generated by Django 5.0.6 on 2024-09-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alarmi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AllarmID", models.SmallIntegerField()),
                (
                    "AllarmString",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("TypeID", models.IntegerField(blank=True, null=True)),
                ("Description_Id", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "告警索引表",
                "verbose_name_plural": "告警索引表",
                "db_table": "[CNC700Cutting].[Alarmi]",
            },
        ),
        migrations.CreateModel(
            name="LiveState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CellaID", models.IntegerField(blank=True, null=True)),
                ("Plant", models.CharField(blank=True, max_length=50)),
                ("Check1", models.DateTimeField(blank=True, null=True)),
                ("Check2", models.DateTimeField(blank=True, null=True)),
                ("Note_Id", models.CharField(blank=True, max_length=50)),
            ],
            options={
                "verbose_name": "在线日志",
                "verbose_name_plural": "在线日志",
                "db_table": "[CNC700Cutting].[LiveState]",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CellaID", models.IntegerField(blank=True, null=True)),
                ("Plant", models.CharField(max_length=50)),
                ("WorkSheetID", models.CharField(max_length=50, null=True)),
                ("OrderID", models.CharField(max_length=50, null=True)),
                ("WorkStatus", models.CharField(max_length=50, null=True)),
                ("Colour", models.CharField(max_length=50, null=True)),
                ("Process", models.CharField(max_length=50, null=True)),
                ("StytleNum", models.CharField(max_length=50, null=True)),
                ("FinishParts", models.CharField(max_length=50, null=True)),
                ("RequireParts", models.CharField(max_length=50, null=True)),
                ("AddReqParts", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "订单表",
                "verbose_name_plural": "订单表",
                "db_table": "[CNC700Cutting].[Order]",
            },
        ),
        migrations.CreateModel(
            name="OrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CellaID", models.IntegerField(blank=True, null=True)),
                ("Plant", models.CharField(max_length=50)),
                ("WorkSheetID", models.CharField(max_length=50, null=True)),
                ("StartTime", models.CharField(max_length=50, null=True)),
                ("StopTime", models.CharField(max_length=50, null=True)),
                ("Status", models.CharField(max_length=50, null=True)),
                ("Mode", models.CharField(max_length=50, null=True)),
                ("PowerOnTM", models.CharField(max_length=50, null=True)),
                ("WorkingTM", models.CharField(max_length=50, null=True)),
                ("FinishParts", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "订单加工记录",
                "verbose_name_plural": "订单加工记录",
                "db_table": "[CNC700Cutting].[OrderHistory]",
            },
        ),
        migrations.CreateModel(
            name="Pezzi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CellaID", models.IntegerField(blank=True, null=True)),
                ("Plant", models.CharField(max_length=50, null=True)),
                ("WorkSheetID", models.CharField(max_length=50, null=True)),
                ("DataTime", models.CharField(max_length=50, null=True)),
                ("Pezzi", models.IntegerField(blank=True, null=True)),
                ("ReqPezzi", models.IntegerField(blank=True, null=True)),
                ("ResidPezzi", models.IntegerField(blank=True, null=True)),
                ("PieceTime", models.IntegerField(blank=True, null=True)),
                ("EstimatedTm", models.CharField(max_length=50, null=True)),
                ("TotWorkTm", models.CharField(max_length=50, null=True)),
            ],
            options={
                "verbose_name": "产量信息日志",
                "verbose_name_plural": "产量信息日志",
                "db_table": "[CNC700Cutting].[Pezzi]",
            },
        ),
        migrations.CreateModel(
            name="Stato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("CellaID", models.IntegerField(blank=True, null=True)),
                ("Plant", models.CharField(max_length=50)),
                ("WorkSheetID", models.CharField(max_length=50, null=True)),
                ("DataTime", models.CharField(max_length=50, null=True)),
                (
                    "Stato",
                    models.BooleanField(
                        blank=True, choices=[(True, "运行"), (False, "停止")], null=True
                    ),
                ),
                ("Alarm", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "工作状态切换日志",
                "verbose_name_plural": "工作状态切换日志",
                "db_table": "[CNC700Cutting].[Stato]",
            },
        ),
    ]
