# Generated by Django 5.0.6 on 2025-03-06 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarmi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40, verbose_name='设备类型')),
                ('AlarmID', models.CharField(max_length=10, verbose_name='告警ID')),
                ('AlarmString', models.CharField(max_length=50, verbose_name='告警信息')),
                ('TypeID', models.IntegerField(blank=True, null=True, verbose_name='类别')),
                ('Description_Id', models.IntegerField(blank=True, null=True, verbose_name='备注索引')),
            ],
            options={
                'verbose_name': '告警索引表',
                'verbose_name_plural': '告警索引表',
                'db_table': '[CNC700Cutting].[Alarmi]',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('CellID', models.IntegerField(verbose_name='机台编号')),
                ('Plant', models.CharField(max_length=40, verbose_name='车间')),
                ('Name', models.CharField(max_length=40, verbose_name='机台')),
                ('Type', models.IntegerField(choices=[(1, '新代系统'), (2, 'PLC')], verbose_name='系统')),
                ('Stato', models.IntegerField(choices=[(0, '作业中'), (1, '待机'), (2, '故障'), (3, '离线')], verbose_name='当前状态')),
                ('IP', models.CharField(blank=True, max_length=20, verbose_name='设备IP')),
                ('Create', models.DateTimeField(verbose_name='创建日期')),
                ('OnLine', models.FloatField(verbose_name='在线时长')),
                ('WorkTM', models.FloatField(verbose_name='作业时长')),
            ],
            options={
                'verbose_name': '设备管理表',
                'verbose_name_plural': '设备管理表',
                'db_table': '[CNC700Cutting].[Cell]',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单号')),
                ('Status', models.CharField(editable=False, max_length=20, null=True, verbose_name='订单状态')),
                ('Colour', models.CharField(max_length=50, null=True, verbose_name='叠加订单')),
                ('Product_id', models.CharField(max_length=50, null=True, verbose_name='产品款号')),
                ('ReqParts', models.IntegerField(blank=True, editable=False, null=True, verbose_name='需求工件数')),
            ],
            options={
                'verbose_name': '订单管理表',
                'verbose_name_plural': '订单管理表',
                'db_table': '[CNC700Cutting].[Order]',
            },
        ),
        migrations.CreateModel(
            name='LiveState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Check1', models.DateTimeField(verbose_name='连线状态时间更新')),
                ('Check2', models.DateTimeField(blank=True, null=True, verbose_name='掉线状态时间更新')),
                ('OnLine', models.FloatField(blank=True, null=True, verbose_name='在线时长-s')),
                ('Cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.cell')),
            ],
            options={
                'verbose_name': '设备在线日志',
                'verbose_name_plural': '设备在线日志',
                'db_table': '[CNC700Cutting].[LiveState]',
            },
        ),
        migrations.CreateModel(
            name='LiveStateManage',
            fields=[
            ],
            options={
                'verbose_name': '设备在线管理',
                'verbose_name_plural': '设备在线管理',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amfui.livestate',),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StartTime', models.DateTimeField(verbose_name='开始时间')),
                ('StopTime', models.DateTimeField(max_length=20, null=True, verbose_name='结束时间')),
                ('Status', models.CharField(max_length=20, null=True)),
                ('Mode', models.CharField(max_length=20, null=True, verbose_name='工作模式')),
                ('FinishParts', models.IntegerField(blank=True, null=True, verbose_name='完成工件数')),
                ('IdleTMSec', models.FloatField()),
                ('PowerOnSec', models.FloatField()),
                ('WorkingSec', models.FloatField()),
                ('EstimatedSec', models.FloatField(blank=True, null=True)),
                ('Cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.cell')),
            ],
            options={
                'verbose_name': '工单加工日志',
                'verbose_name_plural': '工单加工日志',
                'db_table': '[CNC700Cutting].[Record]',
            },
        ),
        migrations.CreateModel(
            name='RecordManage',
            fields=[
            ],
            options={
                'verbose_name': '工单加工记录',
                'verbose_name_plural': '工单加工记录',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amfui.record',),
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='工单号')),
                ('Product_id', models.CharField(max_length=50, verbose_name='款号')),
                ('Status', models.CharField(editable=False, max_length=20, null=True, verbose_name='工单状态')),
                ('ProcessID', models.CharField(max_length=50, null=True, verbose_name='工序备注')),
                ('FinishParts', models.IntegerField(blank=True, editable=False, null=True, verbose_name='完成工件数')),
                ('ReqParts', models.IntegerField(blank=True, editable=False, null=True, verbose_name='需求工件数')),
                ('AddReqParts', models.IntegerField(blank=True, editable=False, null=True, verbose_name='追加工件数')),
                ('Cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.cell')),
                ('Order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.order', verbose_name='订单号')),
            ],
            options={
                'verbose_name': '工单管理表',
                'verbose_name_plural': '工单管理表',
                'db_table': '[CNC700Cutting].[WorkSheet]',
            },
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField(verbose_name='时间')),
                ('Stato', models.IntegerField(choices=[(0, '作业中'), (1, '待机'), (2, '故障'), (3, '离线')], verbose_name='状态切换')),
                ('TimeSpan', models.FloatField(blank=True, null=True, verbose_name='时长-s')),
                ('Alarmi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.alarmi')),
                ('Cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.cell')),
                ('WorkSheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.worksheet')),
            ],
            options={
                'verbose_name': '设备状态切换表',
                'verbose_name_plural': '设备状态切换表',
                'db_table': '[CNC700Cutting].[Stato]',
            },
        ),
        migrations.AddField(
            model_name='record',
            name='WorkSheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.worksheet'),
        ),
        migrations.CreateModel(
            name='Pezzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField(verbose_name='时间')),
                ('Pezzi', models.IntegerField(verbose_name='生产工件数')),
                ('ReqPezzi', models.IntegerField(verbose_name='需求工件数')),
                ('ResidPezzi', models.IntegerField(verbose_name='待生产工件数')),
                ('PieceTime', models.IntegerField(verbose_name='单件加工时长')),
                ('Cell', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.cell')),
                ('WorkSheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.worksheet', verbose_name='工单号')),
            ],
            options={
                'verbose_name': '生产信息日志',
                'verbose_name_plural': '生产信息日志',
                'db_table': '[CNC700Cutting].[Pezzi]',
            },
        ),
        migrations.AddField(
            model_name='livestate',
            name='WorkSheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amfui.worksheet'),
        ),
    ]
