# Generated by Django 5.2.8 on 2025-11-24 20:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False, verbose_name='属性序号')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='属性名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '1.0 基础属性管理',
                'verbose_name_plural': '1.0 基础属性管理',
                'db_table': '[a_wuliao].[Attribute]',
                'ordering': ['description', 'attribute_id'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('material_id', models.AutoField(primary_key=True, serialize=False, verbose_name='物料序号')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='物料编号')),
                ('name', models.CharField(max_length=100, verbose_name='物料名称')),
                ('helpcode', models.CharField(blank=True, max_length=200, null=True, verbose_name='助记码')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='型号')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='来源')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('unit', models.ForeignKey(blank=True, limit_choices_to={'name': '单位'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='a_wuliao.attribute', verbose_name='单位')),
            ],
            options={
                'verbose_name': '1.2 物料管理',
                'verbose_name_plural': '1.2 物料管理',
                'db_table': '[a_wuliao].[Material]',
            },
        ),
        migrations.CreateModel(
            name='BomVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('version', models.CharField(max_length=20, verbose_name='版本号')),
                ('change_reason', models.TextField(blank=True, null=True, verbose_name='变更原因')),
                ('status', models.CharField(choices=[('草稿', '草稿'), ('生效', '生效'), ('失效', '失效'), ('归档', '归档')], default='草稿', max_length=10, verbose_name='状态')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='创建人')),
                ('base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='a_wuliao.bomversion', verbose_name='基础版本')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_versions', to='a_wuliao.material', verbose_name='物料')),
            ],
            options={
                'verbose_name': '1.3 BOM版本管理',
                'verbose_name_plural': '1.3 BOM版本管理',
                'db_table': '[a_wuliao].[BomVersion]',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('quantity', models.DecimalField(decimal_places=4, default=1.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='用量')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='a_wuliao.bomversion', verbose_name='BOM版本')),
                ('c_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_child_boms', to='a_wuliao.material', verbose_name='子物料')),
                ('p_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_parent_boms', to='a_wuliao.material', verbose_name='父物料')),
            ],
            options={
                'verbose_name': '1.4 BOM表管理',
                'verbose_name_plural': '1.4 BOM表管理',
                'db_table': '[a_wuliao].[BOM]',
            },
        ),
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('group_id', models.AutoField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='编号')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='层级')),
                ('group', models.CharField(blank=True, choices=[('01', '成品机'), ('02', '半成品件'), ('03', '外购件'), ('04', '中间件')], max_length=20, null=True, verbose_name='一级分类')),
                ('sub_group', models.CharField(blank=True, choices=[('01.01', '成品整机'), ('01.02', '成品夹具'), ('01.03', '客制模具'), ('01.04', '成品机部件'), ('02.01', '整机钣金件'), ('02.02', '夹具钣金件'), ('02.03', '整机机加件'), ('02.04', '夹具机加件'), ('02.05', 'ZCL标准机加件'), ('02.06', '临时机加件'), ('02.07', '返工类机加件'), ('02.KZ', '客制模具'), ('03.01', '电器类'), ('03.02', '气动类'), ('03.03', '五金类'), ('03.04', '刀具类'), ('03.05', '其它类')], max_length=20, null=True, verbose_name='二级分类')),
                ('min_group', models.CharField(blank=True, max_length=20, null=True, verbose_name='三级分类')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='a_wuliao.materialgroup', verbose_name='父组')),
            ],
            options={
                'verbose_name': '1.1 物料组管理',
                'verbose_name_plural': '1.1 物料组管理',
                'db_table': '[a_wuliao].[MaterialGroup]',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='material',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='a_wuliao.materialgroup', verbose_name='物料组'),
        ),
        migrations.AddConstraint(
            model_name='bomversion',
            constraint=models.UniqueConstraint(fields=('material_id', 'version'), name='pk_bomversion_composite'),
        ),
        migrations.AlterUniqueTogether(
            name='bom',
            unique_together={('version', 'p_material', 'c_material')},
        ),
    ]
