# Generated by Django 5.2.8 on 2025-12-01 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_wuliao', '0001_initial'),
    ]

    operations = [
        # Drop related constraints and indexes first
        migrations.RunSQL("ALTER TABLE [a_wuliao].[BOM] DROP CONSTRAINT a_wuliao_BOM_p_material_id_758d2473_fk_a_wuliao_Material_material_id"),
        migrations.RunSQL("DROP INDEX a_wuliao_BOM_version_id_p_material_id_c_material_id_ab99689a_uniq ON [a_wuliao].[BOM]"),
        migrations.RunSQL("DROP INDEX a_wuliao_BOM_p_material_id_758d2473 ON [a_wuliao].[BOM]"),

        # Alter column to nullable
        migrations.RunSQL("ALTER TABLE [a_wuliao].[BOM] ALTER COLUMN p_material_id INT NULL"),

        # Recreate constraint and index
        migrations.RunSQL("CREATE UNIQUE NONCLUSTERED INDEX a_wuliao_BOM_version_id_p_material_id_c_material_id_uniq ON [a_wuliao].[BOM] (version_id, p_material_id, c_material_id)"),
        migrations.RunSQL("ALTER TABLE [a_wuliao].[BOM] ADD CONSTRAINT a_wuliao_BOM_p_material_id_fk_a_wuliao_Material_material_id FOREIGN KEY (p_material_id) REFERENCES [a_wuliao].[Material](material_id)"),
    ]
