# Generated by Django 5.2.8 on 2025-12-01 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_wuliao', '0002_alter_bom_p_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='p_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='as_parent_boms', to='a_wuliao.material', verbose_name='父物料'),
        ),
    ]
