# Generated by Django 5.1.2 on 2025-04-16 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "Id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="物料编号"
                    ),
                ),
                ("Name", models.CharField(max_length=100, verbose_name="物料名称")),
                ("Type", models.CharField(max_length=100, verbose_name="物料型号")),
                ("Source", models.CharField(max_length=100, verbose_name="获取来源")),
                (
                    "Description",
                    models.TextField(blank=True, null=True, verbose_name="物料描述"),
                ),
            ],
            options={
                "verbose_name": "物料",
                "verbose_name_plural": "物料",
                "db_table": "[CNC700Cutting].[Material]",
            },
        ),
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "Id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="BOM编号"
                    ),
                ),
                ("Quantity", models.IntegerField(verbose_name="数量")),
                (
                    "ParentBOM",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_boms",
                        to="bmui.bom",
                        verbose_name="父级BOM",
                    ),
                ),
                (
                    "Material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bmui.material",
                        verbose_name="物料",
                    ),
                ),
            ],
            options={
                "verbose_name": "物料清单",
                "verbose_name_plural": "物料清单",
                "db_table": "[CNC700Cutting].[BOM]",
            },
        ),
        migrations.CreateModel(
            name="BOMLevel",
            fields=[
                (
                    "Id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="层级编号"
                    ),
                ),
                ("Level", models.IntegerField(default=1, verbose_name="层级")),
                (
                    "BOM",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bmui.bom",
                        verbose_name="物料清单",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM层级",
                "verbose_name_plural": "BOM层级",
                "db_table": "[CNC700Cutting].[BOMLevel]",
            },
        ),
    ]
