# Generated by Django 5.1.2 on 2025-04-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bmui", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="Attribute",
            field=models.TextField(blank=True, null=True, verbose_name="辅助属性"),
        ),
        migrations.AlterField(
            model_name="material",
            name="Description",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
