# Generated by Django 5.1.2 on 2025-11-19 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("a_wuliao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Process",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="删除人"
                    ),
                ),
                (
                    "seqnum",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="工序序列号"
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, null=True, verbose_name="参数"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "3.2 工艺卡",
                "verbose_name_plural": "3.2 工艺卡",
                "db_table": "[c_gongyi].[Process]",
            },
        ),
        migrations.CreateModel(
            name="MaterialParm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="加工尺寸"
                    ),
                ),
                (
                    "stuff",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="材料"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="材料成本",
                    ),
                ),
                (
                    "surface",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="表面处理"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "bom_ver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_wuliao.bomversion",
                        verbose_name="物料版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.0 工艺参数",
                "verbose_name_plural": "3.0 工艺参数",
                "db_table": "[c_gongyi].[MaterialParm]",
            },
        ),
        migrations.CreateModel(
            name="Craft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "params",
                    models.TextField(blank=True, null=True, verbose_name="参数"),
                ),
                (
                    "process",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="c_gongyi.process",
                        verbose_name="工序流程",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.2.1 工艺配方",
                "verbose_name_plural": "3.2.1 工艺配方",
                "db_table": "[c_gongyi].[Craft]",
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="删除人"
                    ),
                ),
                (
                    "is_cnc",
                    models.BooleanField(default=False, verbose_name="是否CNC工艺流程"),
                ),
                ("product_id", models.CharField(max_length=50, verbose_name="款号")),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "草稿"),
                            ("approved", "已批准"),
                            ("rejected", "已拒绝"),
                        ],
                        default="draft",
                        max_length=40,
                        verbose_name="状态",
                    ),
                ),
                (
                    "params",
                    models.JSONField(blank=True, null=True, verbose_name="参数"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="备注索引"),
                ),
                (
                    "bom_ver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_wuliao.bomversion",
                        verbose_name="物料版本",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.3 工艺流程",
                "verbose_name_plural": "3.3 工艺流程",
                "db_table": "[c_gongyi].[Route]",
                "unique_together": {("bom_ver", "is_cnc")},
            },
        ),
        migrations.AddField(
            model_name="process",
            name="route",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_steps",
                to="c_gongyi.route",
                verbose_name="工艺流程",
            ),
        ),
        migrations.AddField(
            model_name="process",
            name="subroute",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_steps",
                to="c_gongyi.route",
                verbose_name="CNC工艺流程",
            ),
        ),
        migrations.CreateModel(
            name="VirtualProcessRoute",
            fields=[],
            options={
                "verbose_name": "3.4 流程管理",
                "verbose_name_plural": "3.4 流程管理",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("c_gongyi.route",),
        ),
        migrations.CreateModel(
            name="Step",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否删除"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="删除时间"
                    ),
                ),
                (
                    "deleted_by",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="删除人"
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="工序名称")),
                (
                    "ucost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="工序计件单价/元",
                    ),
                ),
                (
                    "hcost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="工序计时单价/元",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"description": "工序分类"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="a_wuliao.attribute",
                        verbose_name="工序分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "3.1 工序管理",
                "verbose_name_plural": "3.1 工序管理",
                "db_table": "[c_gongyi].[Step]",
                "unique_together": {("name", "type")},
            },
        ),
        migrations.AddField(
            model_name="process",
            name="steps",
            field=models.ManyToManyField(
                blank=True,
                through="c_gongyi.Craft",
                to="c_gongyi.step",
                verbose_name="工序列表",
            ),
        ),
        migrations.AddField(
            model_name="craft",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="c_gongyi.step",
                verbose_name="工序",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="process",
            unique_together={("route", "seqnum")},
        ),
    ]
