# Generated by Django 5.2.8 on 2025-12-05 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_gongyi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNCCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField(help_text='工步在工序中的顺序', verbose_name='工步序号')),
                ('params', models.JSONField(blank=True, help_text='存储刀具、速度等参数的JSON数据', null=True, verbose_name='参数')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_gongyi.step', verbose_name='工步')),
            ],
            options={
                'verbose_name': '4.2 CNC工步详情',
                'verbose_name_plural': '4.2 CNC工步详情',
                'db_table': '[c_gongyi].[CNCCraft]',
            },
        ),
        migrations.CreateModel(
            name='CNCProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('seqnum', models.IntegerField(blank=True, null=True, verbose_name='工序号')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='参数')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnc_processes', to='c_gongyi.route', verbose_name='CNC工艺流程')),
                ('steps', models.ManyToManyField(blank=True, through='c_gongyi.CNCCraft', to='c_gongyi.step', verbose_name='工步列表')),
            ],
            options={
                'verbose_name': '4.1 CNC工序',
                'verbose_name_plural': '4.1 CNC工序',
                'db_table': '[c_gongyi].[CNCProcess]',
                'unique_together': {('route', 'seqnum')},
            },
        ),
        migrations.AddField(
            model_name='cnccraft',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_steps', to='c_gongyi.cncprocess', verbose_name='工序卡片'),
        ),
        migrations.CreateModel(
            name='CNCProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('program_name', models.CharField(help_text='CNC程序文件名', max_length=100, verbose_name='程序名称')),
                ('equipment_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备型号')),
                ('fixture_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='夹具名称')),
                ('simulation_time', models.IntegerField(blank=True, null=True, verbose_name='模拟时间(分)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('path', models.CharField(blank=True, max_length=200, null=True, verbose_name='程序路径')),
                ('cnc_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='c_gongyi.cncprocess', verbose_name='CNC工序')),
            ],
            options={
                'verbose_name': '4.3 CNC程序',
                'verbose_name_plural': '4.3 CNC程序',
                'db_table': '[c_gongyi].[CNCProgram]',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cnccraft',
            unique_together={('process', 'step_num')},
        ),
    ]
