# Generated by Django 5.1.2 on 2025-05-31 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POrder",
            fields=[
                (
                    "CreateTime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "UpdateTime",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "IsDelete",
                    models.BooleanField(default=False, verbose_name="是否删除"),
                ),
                (
                    "IsActive",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "OrderId",
                    models.CharField(
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        verbose_name="订单号",
                    ),
                ),
                (
                    "Status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="订单状态"
                    ),
                ),
                (
                    "Product_id",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="产品编号"
                    ),
                ),
                (
                    "DeadLine",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="交货日期"
                    ),
                ),
                (
                    "Owner",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="制单员"
                    ),
                ),
                (
                    "WH",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="仓库员"
                    ),
                ),
                (
                    "Audit",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="审计员"
                    ),
                ),
                (
                    "Cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="成本",
                    ),
                ),
                (
                    "LotId",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="批次号"
                    ),
                ),
                (
                    "Description",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "产品订单管理",
                "verbose_name_plural": "产品订单管理",
                "db_table": "[jihuaManagerUI].[POrder]",
            },
        ),
        migrations.CreateModel(
            name="OutBoundManag",
            fields=[],
            options={
                "verbose_name": "订单外发管理",
                "verbose_name_plural": "订单外发管理",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("jihuaManagerUI.porder",),
        ),
    ]
