# Generated by Django 4.2.2 on 2023-07-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AllarmID', models.SmallIntegerField()),
                ('AllarmString', models.CharField(blank=True, max_length=50, null=True)),
                ('TypeID', models.IntegerField(blank=True, null=True)),
                ('Description_Id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '[zclDb].[Alarmi]',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('EventID', models.IntegerField(primary_key=True, serialize=False)),
                ('Data', models.CharField(max_length=100)),
                ('Ora', models.CharField(max_length=100)),
                ('Plant', models.CharField(max_length=50, null=True)),
                ('CellaID', models.IntegerField(blank=True, null=True)),
                ('Microlotto', models.IntegerField(blank=True, null=True)),
                ('Modello', models.CharField(max_length=50, null=True)),
                ('Calibro', models.IntegerField(blank=True, null=True)),
                ('Colore', models.CharField(max_length=50, null=True)),
                ('Pezzi', models.IntegerField(blank=True, null=True)),
                ('Evento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '[zclDb].[Event]',
            },
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('ordernumber', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=10, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('model', models.CharField(max_length=20, null=True)),
                ('cal', models.CharField(max_length=10, null=True)),
                ('color', models.CharField(max_length=10, null=True)),
                ('material', models.CharField(max_length=10, null=True)),
                ('quantity', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': '[zclDb].[Incoming]',
            },
        ),
        migrations.CreateModel(
            name='LiveStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plant', models.CharField(blank=True, max_length=50)),
                ('CellaID', models.IntegerField(blank=True, null=True)),
                ('Check1', models.DateTimeField(blank=True, null=True)),
                ('Check2', models.DateTimeField(blank=True, null=True)),
                ('Note_Id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '[zclDb].[LiveState]',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MessageID', models.IntegerField()),
                ('MessageString', models.CharField(max_length=4000, null=True)),
                ('Description_Id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '[zclDb].[Messaggi]',
            },
        ),
        migrations.CreateModel(
            name='Pezzi',
            fields=[
                ('EventID', models.IntegerField(primary_key=True, serialize=False)),
                ('Data', models.CharField(max_length=100, null=True)),
                ('Plant', models.CharField(max_length=50, null=True)),
                ('CellaID', models.IntegerField(blank=True, null=True)),
                ('MainProg', models.CharField(max_length=100, null=True)),
                ('Pezzi', models.IntegerField(blank=True, null=True)),
                ('Ora', models.CharField(max_length=100, null=True)),
                ('JobMode', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': '[zclDb].[Pezzi]',
            },
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('StatoID', models.IntegerField(primary_key=True, serialize=False)),
                ('Data', models.CharField(max_length=100)),
                ('Ora', models.CharField(max_length=100)),
                ('Plant', models.CharField(max_length=50)),
                ('CellaID', models.IntegerField(blank=True, null=True)),
                ('Stato', models.BooleanField(blank=True, choices=[(1, '运行'), (0, '停止')], null=True)),
                ('Alarm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': '[zclDb].[Stato]',
            },
        ),
    ]
