# Generated by Django 5.2.8 on 2025-12-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('b_jihua', '0003_orderparts_version'),
        ('c_gongyi', '0002_cnccraft_cncprocess_cnccraft_process_cncprogram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('status', models.CharField(default='draft', max_length=50, verbose_name='状态')),
                ('planned_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='计划数量')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='计划日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_jihua.orderparts', verbose_name='订单零件')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_gongyi.route', verbose_name='工艺路线')),
            ],
            options={
                'verbose_name': '4.0 排产计划',
                'verbose_name_plural': '4.0 排产计划',
                'db_table': '[d_paichan].[ProductionPlan]',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='生产订单号')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='状态')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_paichan.productionplan', verbose_name='排产计划')),
            ],
            options={
                'verbose_name': '4.1 生产订单',
                'verbose_name_plural': '4.1 生产订单',
                'db_table': '[d_paichan].[ProductionOrder]',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='删除人')),
                ('sequence', models.IntegerField(verbose_name='工序序列')),
                ('status', models.CharField(default='pending', max_length=50, verbose_name='状态')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('assigned_to', models.CharField(blank=True, max_length=50, null=True, verbose_name='分配到')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('description', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='d_paichan.productionorder', verbose_name='生产订单')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_gongyi.step', verbose_name='工序')),
            ],
            options={
                'verbose_name': '4.2 任务工单',
                'verbose_name_plural': '4.2 任务工单',
                'db_table': '[d_paichan].[WorkOrder]',
            },
        ),
    ]
