# Generated by Django 5.2.8 on 2025-12-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('d_paichan', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE VIEW [d_paichan].[VProductionPlan] AS
            SELECT id, create_time, update_time, is_deleted, deleted_at, deleted_by, order_part_id, route_id, status, planned_quantity, planned_date, description, id as original_id
            FROM [d_paichan].[ProductionPlan]
            UNION ALL
            SELECT NULL as id, op.create_time, op.update_time, op.is_deleted, op.deleted_at, op.deleted_by, op.id as order_part_id, NULL as route_id, '请设定加工工艺' as status, op.quantity as planned_quantity, op.deadline as planned_date, op.description, NULL as original_id
            FROM [b_jihua].[OrderParts] op
            LEFT JOIN [d_paichan].[ProductionPlan] pp ON op.id = pp.order_part_id AND pp.is_deleted = 0
            WHERE pp.id IS NULL AND op.is_deleted = 0
            """,
            """
            DROP VIEW IF EXISTS [d_paichan].[VProductionPlan]
            """,
        ),
    ]
